[custom]
;*****局域网*****

;10.10.10.100-10.10.10.255
ruleset=🏠局域网DHCP,clash-classic:https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/dhcp-ip.yaml

;10721,20721,30721,40721,50721,60721
ruleset=🟢直接连接,https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/port.list

;*****规则集*****
ruleset=🚫广告拦截,https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/none.list
ruleset=🍃应用净化,https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/none.list
ruleset=🛡️隐私防护,https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/none.list
ruleset=⚪白名单,https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/white.list
ruleset=🟢直接连接,clash-classic:https://raw.githubusercontent.com/Femoon/clash-rules/master/steam.yaml
ruleset=🎌日本限定,https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/connected.list
ruleset=☁️PikPak网盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PikPak/PikPak.list
ruleset=☁️Docker服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Docker/Docker.list
ruleset=🔗群晖服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Synology/Synology.list
ruleset=🔗Akamai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Akamai/Akamai.list
ruleset=📹国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=📺YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🎵Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
ruleset=👨‍💻GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🍎苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=🪟微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🕊谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=✉️邮箱服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Mail/Mail.list
ruleset=🔈电报服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🤖OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖Civitai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Civitai/Civitai.list
ruleset=🎮STEAM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Steam.list
ruleset=🎮EPIC,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Epic.list
ruleset=🚫PicACG,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Picacg/Picacg.list
ruleset=🚫EHGallery,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/EHGallery/EHGallery.list
ruleset=📹国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=📹国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Tmdb/Tmdb.list
ruleset=✖️推特信息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list
ruleset=💻群晖本机,clash-classic:https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/synology-host.yaml
ruleset=🟢直接连接,[]GEOSITE,CN
ruleset=🟢直接连接,[]GEOIP,CN,no-resolve
ruleset=🔒锁定搬家🏠,[]GEOSITE,geolocation-!cn
ruleset=🛠️境外连接,clash-classic:https://raw.githubusercontent.com/Pauldada/clash-config/refs/heads/main/rule/synology-ipv4.yaml
ruleset=🐟漏网之鱼,[]FINAL

;*****策略组*****
custom_proxy_group=🚀节点选择`select`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🔒锁定搬家🏠`select`(^(?!.*(广港|沪日|沪韩|剩余|流量)).*)`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=🔒️锁定链路⛓️`select`(?=.*(广港|沪日|沪韩))^((?!(剩余|流量|IEPL)).)*$
custom_proxy_group=🔗群晖服务`select`[]🔒锁定搬家🏠`[]🟢直接连接`[]🔴拒绝连接`[]🔒️锁定链路⛓️`[]🚀节点选择
custom_proxy_group=💻群晖本机`select`[]🔒锁定搬家🏠`[]🟢直接连接`[]🔴拒绝连接`[]🔒️锁定链路⛓️`[]🚀节点选择
custom_proxy_group=🛠️境外连接`select`[]🔒锁定搬家🏠`[]🟢直接连接`[]🔴拒绝连接`[]🔒️锁定链路⛓️`[]🚀节点选择
custom_proxy_group=🔗Akamai`select`[]🔒锁定搬家🏠`[]🟢直接连接`[]🔴拒绝连接`[]🔒️锁定链路⛓️`[]🚀节点选择
custom_proxy_group=🎌日本限定`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=☁️Docker服务`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=☁️PikPak网盘`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🤖OpenAI`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🤖Civitai`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=👨‍💻GitHub`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🐟漏网之鱼`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🎵Spotify`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=📺YouTube`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=📹国外媒体`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🕊谷歌服务`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=✖️推特信息`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🔈电报服务`select`[]🚀节点选择`[]🟢直接连接`[]🔴拒绝连接`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=📹国内媒体`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=✉️邮箱服务`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=🎮STEAM`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=🎮EPIC`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=🚫PicACG`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾
custom_proxy_group=🚫EHGallery`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🪟微软服务`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🍎苹果服务`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🏠局域网DHCP`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=⚪白名单`select`[]🟢直接连接`[]🔴拒绝连接`[]🚀节点选择`[]🔒锁定搬家🏠`[]🔒️锁定链路⛓️`[]📦日本`[]📦香港`[]📦台湾`[]📦韩国`[]📦美国`[]📦印度`[]📦泰国`[]📦蒙古`[]📦越南`[]📦印尼`[]📦荷兰`[]📦英国`[]📦德国`[]📦法国`[]📦波兰`[]📦新加坡`[]📦加拿大`[]📦俄罗斯`[]📦土耳其`[]📦阿根廷`[]📦马来西亚`[]📦巴基斯坦`[]📦澳大利亚
custom_proxy_group=🚫广告拦截`select`[]🔴拒绝连接`[]🟢直接连接`[]🚀节点选择
custom_proxy_group=🍃应用净化`select`[]🔴拒绝连接`[]🟢直接连接`[]🚀节点选择
custom_proxy_group=🛡️隐私防护`select`[]🔴拒绝连接`[]🟢直接连接`[]🚀节点选择

;*****策略引用*****
custom_proxy_group=🟢直接连接`select`[]DIRECT
custom_proxy_group=🔴拒绝连接`select`[]REJECT
custom_proxy_group=📦日本`url-test`(?=.*(日本))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=📦香港`url-test`(?=.*(香港))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=📦台湾`url-test`(?=.*(台湾))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=📦韩国`url-test`(?=.*(韩国))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦美国`url-test`(?=.*(美国))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦印度`url-test`(?=.*(印度))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦泰国`url-test`(?=.*(泰国))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦蒙古`url-test`(?=.*(蒙古))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦越南`url-test`(?=.*(越南))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦印尼`url-test`(?=.*(印尼))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦荷兰`url-test`(?=.*(荷兰))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦英国`url-test`(?=.*(英国))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦德国`url-test`(?=.*(德国))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦法国`url-test`(?=.*(法国))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦波兰`url-test`(?=.*(波兰))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦新加坡`url-test`(?=.*(新加坡))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦加拿大`url-test`(?=.*(加拿大))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦俄罗斯`url-test`(?=.*(俄罗斯))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦土耳其`url-test`(?=.*(土耳其))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦阿根廷`url-test`(?=.*(阿根廷))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦马来西亚`url-test`(?=.*(马来西亚))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦巴基斯坦`url-test`(?=.*(巴基斯坦))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100
custom_proxy_group=📦澳大利亚`url-test`(?=.*(澳大利亚))^((?!(剩余|流量|IPLC|2.0|3.0|4.0|5.0|6.0)).)*$`http://www.gstatic.com/generate_204`600,,100

enable_rule_generator=true
overwrite_original_rules=true
